require("utils")

vim.g.mapleader = " "

vim.cmd("hi Pmenu ctermfg=NONE ctermbg=236 cterm=NONE")
vim.cmd("hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE")

vim.cmd("syntax enable")
vim.cmd("filetype plugin indent on")
opt("showmode", false)
opt("ruler", false)
opt("showcmd", false)
opt("laststatus", 2)
opt("statusline", " ")
opt("mouse", "a")
opt("autoindent")
opt("expandtab")
opt("shiftround")
opt("shiftwidth", 2)
opt("smarttab")
opt("tabstop", 2)
opt("autoread")
opt("hlsearch")
opt("incsearch")
opt("ignorecase")
opt("smartcase")
opt("lazyredraw")
opt("tabpagemax", 10)
opt("linebreak")
opt("scrolloff", 7)
opt("wildmenu")
opt("number")
opt("errorbells", false)
opt("title")
opt("backspace", "indent,eol,start")
opt("confirm")
opt("history", 100)
opt("splitbelow")
opt("splitright")
opt("showmatch")
opt("clipboard", "unnamed")
opt("hidden")
opt("signcolumn", "number")
opt("swapfile", false)
opt("cmdheight", 2)

aopt("shortmess", "c")
aopt("fillchars", "vert: ,eob: ")
aopt("shm", "I")
