#!/usr/bin/env sh

spacebar -m config height                   25
spacebar -m config space_icon_strip         1 2 3 4 5 6 7 8 9 0
spacebar -m config text_font                "Hack Nerd Font Mono:Bold:12.0"
spacebar -m config icon_font                "Hack Nerd Font Mono:Bold:12.0"
spacebar -m config background_color         0xFF000000
spacebar -m config foreground_color         0xFFA8A8A8
spacebar -m config space_icon_color         0xFF4469AC
spacebar -m config clock_icon               " "
spacebar -m config title                    off

# spacebar -m config center_shell on
# spacebar -m config center_shell_command "echo $(icalbuddy -ps "/ » /" -li 1 -iep "title,datetime" -eed -n -ea -nc -nrd -npn --includeCals berend@animo.id eventsToday)"
