export EDITOR="nvim"
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export JAVA_HOME="/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home"
export DOCKER_HOST="unix:///var/run/docker.sock"
export XDG_CONFIG_HOME="$HOME/.config"
export FZF_DEFAULT_OPTS='--color=bw'
export VOLTA_HOME="$HOME/.volta"
export N_PREFIX="$HOME/.n"
export HOMEBREW_NO_AUTO_UPDATE=1
