export EDITOR="nvim"
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export ANDROID_HOME=$ANDROID_SDK_ROOT
export ANDROID_AVD_HOME="$XDG_CONFIG_HOME/.android/avd"
export JAVA_HOME="/usr/lib/jvm/default"
export DOCKER_HOST="unix:///var/run/docker.sock"
export XDG_CONFIG_HOME="$HOME/.config"
export FZF_DEFAULT_OPTS='--color=bw'
export VOLTA_HOME="$HOME/.volta"
export N_PREFIX="$HOME/.n"
export HOMEBREW_NO_AUTO_UPDATE=1
