source $HOME/.config/zsh/sources.zsh

# # pnpm
# export PNPM_HOME="/Users/beri/Library/pnpm"
# case ":$PATH:" in
#   *":$PNPM_HOME:"*) ;;
#   *) export PATH="$PNPM_HOME:$PATH" ;;
# esac
# # pnpm end
# 
# export DISPLAY=:0
